### ISSUE TITLE
Is mutation having too much of an effect?

### ISSUE THREAD

**Issue by daffidwilde** [daffidwilde/edo#24]
# Summary

Given a long enough time, the noise in the GA becomes prevelant and the population fitnesses seem to spread. Jumps in fitness like this are controlled by the mutation process. In a similar vein to the sampling issues we had before with families of datasets, individual datasets are delicate objects it would seem and the mutation process has the ability to be destructive throughout the algorithm.

# Example

Take the sample mean example. Each individual is a single-column dataset, `X`, of length between 5 and 50 instances and is generated by sampling a set of numbers from a member of the family of normal distributions described below. Take some random sample of five elements from `X` and call it `Y`. The fitness function is given by `mean(Y) ** 2` and the objective is to minimise this function.

Allow there to be 100 individuals in the population, and run the GA using the default parameters for 50 iterations:

``` python
import genetic_data as gd
import matplotlib.pyplot as plt

def sample_mean_squared(df):
    return df.sample(5, replace=True).mean().mean() ** 2

pop, fit, all_pops, all_fits = gd.run_algorithm(
    fitness=sample_mean_squared,
    size=100,
    row_limits=[5, 50],
    col_limits=[1, 1],
    max_iter=50,
    maximise=False,
    seed=0
)

fig, ax = plt.subplots(1, figsize=(40, 20), dpi=300)

ax.boxplot(all_fits, positions=range(len(all_fits)), sym='.')

ax.set_title('Fitness scores in each epoch', size=24, pad=25)
ax.set_yscale('log')
ax.set_xlabel('Epoch', size=24)
ax.set_ylabel(r'$\log(f(X))$', size=24)

for label in ax.get_xticklabels() + ax.get_yticklabels():
    label.set_fontsize(20)

plt.show()
```

![divergence](https://user-images.githubusercontent.com/26261131/43452822-54cf8e6e-94b0-11e8-8ec3-474011326cee.png)

# Suggested fixes

#### Using another stopping condition based on the quality of a population's fitness:
This wouldn't actually stop the behaviour, a well-defined condition would just terminate the algorithm before it happens.

#### Dwindling mutation probability:
As the algorithm progresses, it shows signs of convergence so decreasing the likelihood of a mutation happening would stop the GA from altering too many "good" solutions.

#### Decreasing the mutation space:
The way in which mutation of a value occurs in this GA is to sample from the normal distribution centred at the current value with standard deviation given by `sigma` (defaulted to 1). In hindsight, this has meant that for small values, relatively large changes will likely happen during mutation, having a substantial effect on the overall fitness of that individual. Moving away from this fixed sigma approach towards something relative to the individual at hand could be beneficial.

Not that it affects the example here too much (since the GA is restricted to generating datasets with exactly one column) but new columns are added to a dataset in mutation by effectively initialising a column of the correct length and sticking it on the end. Columns are generated by sampling from a list of `pdf` objects which sample their parameters from preset ranges upon becoming an instance of that class. For example, a normally distributed column pdf will take a mean in the interval [-10, 10] and standard deviation in the range [0, 10]. This is a deliberately wide range for the initial population but later on this could cause problems when a dataset is near-uniform, for instance. Allowing these ranges to diminish over time would soften the impact of mutation. Another option is to simply take a new column to be a copy of a column currently in the dataset. That could mean that the change would have too small an effect on the fitness of the individual, however.

**Comment by daffidwilde** [comment]
Will look to implement both dwindling mutation probability and reducing parameter space. Otherwise, the reason for this behaviour has been put down to a lack of smoothing in the fitness function. Smoothing is used to accommodate the noise that comes with randomly sampling rows of the dataset being evaluated, and instead amalgamating the fitness obtained from several samples.

**Comment by drvinceknight** [comment]
> Will look to implement both dwindling mutation probability and reducing parameter space. Otherwise, the reason for this behaviour has been put down to a lack of smoothing in the fitness function. Smoothing is used to accommodate the noise that comes with randomly sampling rows of the dataset being evaluated, and instead amalgamating the fitness obtained from several samples.

I'd suggest closing this issue and open another issue for dwindling mutation probability :+1:

**Comment by daffidwilde** [comment]
Right you are. See #50
